export const sendas = [
  { de: "keter", a: "chochmah" },
  { de: "keter", a: "binah" },
  { de: "chochmah", a: "binah" },
  { de: "chochmah", a: "chesed" },
  { de: "chochmah", a: "tiferet" },
  { de: "binah", a: "gevurah" },
  { de: "binah", a: "tiferet" },
  { de: "keter", a: "tiferet" },
  { de: "chesed", a: "gevurah" },
  { de: "chesed", a: "tiferet" },
  { de: "gevurah", a: "tiferet" },
  { de: "tiferet", a: "netzach" },
  { de: "tiferet", a: "hod" },
  { de: "netzach", a: "hod" },
  { de: "netzach", a: "yesod" },
  { de: "hod", a: "yesod" },
  { de: "yesod", a: "malkuth" },
  { de: "binah", a: "hod" },
  { de: "chochmah", a: "netzach" },
  { de: "gevurah", a: "hod" },
  { de: "chesed", a: "netzach" },
  { de: "daat", a: "netzach" },
  { de: "daat", a: "hod" },
  { de: "daat", a: "yesod" }
];
